name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/docs.yml
      - .jazzy.yaml
      - "Sources/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
          workflow_id: 1778578
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate Jazzy Docs
        run: jazzy
      - name: Publish to GitHub Pages
        run: |
          cd docs
          git init
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m 'Deploy updated Jazzy docs'
          git push -f https://${{ secrets.DOCS_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git master:gh-pages
