name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: "norionomura/jazzy"

    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
      - uses: actions/checkout@v2
      - name: Run SourceKitten
        run: sourcekitten doc --spm-module SwiftShortcuts > SwiftShortcuts.json
      - name: Generate Jazzy Docs
        run: jazzy --sourcekitten-sourcefile SwiftShortcuts.json
      - name: Publish to GitHub Pages
        run: |
          cd docs
          git init
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m 'Deploy updated Jazzy docs'
          git push -f https://${{ secrets.DOCS_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git master:gh-pages
